# Generated by Django 2.2.4 on 2019-08-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toluapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
